config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'pages#home'

  resources :bikes, only: [:index, :show, :new, :create]

  resources :bikes do
    resources :reviews, only: :create
  end

  resources :bikes do
      resources :bookings
  end

  resources :profiles do
    resources :bikes, shallow: true
  end

end

app/models/bike.rb
class Bike < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :user
  validates :model, presence: true
  validates :year, presence: true, format: {
    with: /(19|20)\d{2}/i,
    message: "should be a four-digit year"
    }
  validates :displacement, presence: true
  validates :brand, presence: true
  validates :bike_type, presence: true, inclusion: { in: %w(Moped Scooter Motorcycle), message: "%{value} is not a valid category" }
  validates :address, presence: { message: "Address must be in valid format" }
  # validates :rating, numericality: { only_integer: true,
  #   less_than_or_equal_to: 5,
  #   greater_than_or_equal_to: 0
  #   }
  # # has_one :user, through: :booking
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :bike
  belongs_to :user
  validates :checkin, presence: true
  validates :checkout, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :bike
  belongs_to :user
  validates :description, :presence => { :message => "Description is mandatory, please specify one" }, length: {minimum: 10}
  validates :rating, :presence => { :message => "Rating is mandatory, please specify one" },
  numericality: { only_integer: true,
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0
  }
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  validates :owner, inclusion: { in: [true, false] }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile, dependent: :destroy
  has_many :bikes, dependent: :destroy
  has_many :bookings
  has_many :reviews


  validates :email, presence: true, format: {
   with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
   message: "invalid email"
 }

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  after_create :send_welcome_email


   def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  # private
  def index
    @bikes = Bike.all
    # @bikes = Bike.where(address: params[:city])
    if (params[:checkin] != '' && params[:checkout] != '')
      Booking.all.each do |booking|
        if (Date.parse(params[:checkin]) >= Date.parse(booking.checkin)) && (Date.parse(params[:checkin]) <= Date.parse(booking.checkout))
          @bikes = @bikes - [Bike.find(booking.bike_id)]
        elsif  (Date.parse(params[:checkout]) >= Date.parse(booking.checkin)) && (Date.parse(params[:checkout]) <= Date.parse(booking.checkout))
          @bikes = @bikes - [Bike.find(booking.bike_id)]
        elsif Date.parse(params[:checkout]) - Date.parse(params[:checkin]) > Date.parse(booking.checkout) - Date.parse(booking.checkin)
          @bikes = @bikes - [Bike.find(booking.bike_id)]
        end
      end

    end

    @markers = Gmaps4rails.build_markers(@bikes) do |bike, marker|
      marker.lat bike.latitude
      marker.lng bike.longitude
    end
  end

  def show
    @booking = Booking.new
    @bike = Bike.find(params[:id])
    @review = Review.new
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user

    if @bike.save
      flash[:notice] = "Bike #{@bike.brand} #{@bike.model} has been created"
      redirect_to bike_path(@bike)
    else
      flash[:alert] = "Bike #{@bike.brand} #{@bike.model} has not been created"
      render :new
    end
  end

  private

  def bike_params
    params.require(:bike).permit(:description, :model, :year, :displacement, :brand, :bike_type, :address, :mileage, :rate, :photo, :photo_cache)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new(booking_params)
    @booking.bike_id = params[:bike_id]
    @booking.user_id = User.find(current_user).id
    if @booking.save
      flash[:notice] = "Booking from #{@booking.checkin} to #{@booking.checkout} has been created"
      redirect_to bike_bookings_path(@bike)
    else
      flash[:alert] = "Booking from #{@booking.checkin} to #{@booking.checkout} has not been created"
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:bike, :checkin, :checkout)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :find_profile, only: [:show, :edit, :update]

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    @profile.save
    redirect_to profile_path(@profile)
  end

  def show
    if @profile.nil?
      redirect_to new_profile_path
    end
  end

  def edit
  end

  def update
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end

  private

  def find_profile
    @profile = Profile.find_by_user_id(current_user)
  end

  def profile_params
    params.require(:profile).permit(:name, :address, :phone_number, :photo, :photo_cache)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @bike = Bike.find(params[:bike_id])
    @review = Review.new(review_params)
    @review.bike = @bike
    @review.user = current_user
    if @review.save!
      respond_to do |format|
        format.html { redirect_to bike_path(@bike) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'bikes/show' }
        format.js
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
  def rate(note)
    return 0 if note == nil
    note
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bikes/_form.html.erb
<%= simple_form_for(@bike) do |f| %>
  <%= f.error_notification %>

  <%= f.input :bike_type, collection: [ "Moped", "Scooter", "Motorcycle"]%>
  <%= f.input :brand %>
  <%= f.input :model %>
  <%= f.input :displacement %>
  <%= f.input :year %>
  <%= f.input :mileage %>
  <%= f.input :address %>
  <%= f.input :description, as: :text %>
  <%= f.input :rate, label: "Daily rate (€)" %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

  <%= f.button :submit %>
<% end %>

app/views/bikes/index.html.erb
<div class="fluid-container">

  <div class="row nomargin">
    <div class="col-xs-12 col-md-7 leftcol">

      <div class="outer-listings-container row-space-2">
        <div class="listings-container">
          <div class="row">
            <% @bikes.each do |bike| %>
            <div class="col-xs-12 col-sm-6 row-space-2">
              <div class="listing-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path bike.photo %>);">
                <div class="listing-card-category"><%= bike.bike_type %></div>
                <div class="listing-card-description">
                  <h2><%= bike.brand %> <%= bike.model %></h2>
                </div>
                <div class="listing-card-rate">
                  <%= bike.rate %> €
                </div>
                <%= cl_image_tag bike.user.profile.photo, width: 30, height: 30, crop: :fill, class: "listing-card-user avatar" %>
                <%= link_to '', bike_path(bike), class: 'listing-card-link'%>
              </div>
            </div>
            <% end %>
          </div>
          <% content_for(:after_js) do %>
          <%= javascript_tag do %>
          $(document).on('ready', function() {
          handler = Gmaps.build('Google');
          handler.buildMap({ internal: { id: 'map' } }, function(){
          markers = handler.addMarkers(<%= raw @markers.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      })
      <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-xs-12 col-md-5 rightcol nopadding">
  <div id="map" style="width: 100%; height: 100%;"></div>



  <script type="text/javascript">
    var myLatlng = new google.maps.LatLng(48.852937,2.364178);

    var myOptions = {
      zoom: 16,
      center: myLatlng,
      scrollwheel: false,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
          styles: [] // TODO: replace [] by array from https://snazzymaps.com/
        };

        var map = new google.maps.Map(document.getElementById('map'), myOptions);
        var marker = new google.maps.Marker({
          position: myLatlng,
          map: map,
          title: "You are here!"
        });
      </script>
    </div>
  </div>

</div>
<%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
<%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

app/views/bikes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

     <h3>New Listing</h3>
     <%= render 'form' %>
     <hr>
     <%= link_to 'Return to main page', root_path %>

   </div>
 </div>
</div>

app/views/bikes/show.html.erb
<div class="banner banner-bike" style="background-image: url(<%= cl_image_path @bike.photo %>);"></div>


<div class="container-show-origin">
  <div class="row">
    <div class="col-xs-12 col-sm-3 col-offset-1 text-center flat-row">
      <h4>OWNER</h4>
      <%= link_to profile_path(@bike.user.profile) do %>
      <%= cl_image_tag @bike.user.profile.photo, width: 150, height: 150, radius: "max", crop: :fill %>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-4 col-offset-1">
      <h3><%= @bike.brand %></h3>
      <p><%= @bike.model %></p>
      <p><%= @bike.year %></p>
      <ul class="list-inline">
        <li style="color: gold">
          <% rate(@bike.rating).times do %>
          <i class="fa fa-star"></i>
          <% end %>
        </li>
        <li>
          <% (5 - rate(@bike.rating)).times do %>
          <i class="fa fa-star-o"></i>
          <% end %>
        </li>
      </ul>

    </div>

    <div class="container-show col-xs-12 col-sm-4 col-offset-1 text-center">
      <h3>Book this <%= @bike.bike_type %></h3>
      <h4><%= @bike.rate %> € / Day</h4>

      <div id="sandbox-container">
        <%= simple_form_for [@bike, @booking] do |f| %>
        <%= f.error_notification %>

        <%= f.input :checkin, :input_html => { :placeholder => "Choose your date", :class => "form-control", :data => {:provide => "datepicker"} }%>
        <%= f.input :checkout, :input_html => { :placeholder => "Choose your date", :class => "form-control", :data => {:provide => "datepicker"} }%>

        <%= f.button :submit, class: "btn btn-danger", value: "Book it", style: "width: 100%" %>
        <% end %>
      </div>

    </div>
  </div>
</div>



<div class="wrapper-show">
  <div class="container-specs">
    <div class="row">

      <div class="col-xs-12 col-sm-4 col-offset-1 text-center flat-row">
        <h3>Specifications</h3><br>
        <ul>
          <li> Category: <%= @bike.bike_type %></li><br>
          <li> Displacement: <%= @bike.displacement %></li><br>
          <li> Mileage: <%= @bike.mileage %></li><br>
        </ul>
      </div>

      <div class="col-xs-12 col-sm-8 col-offset-1 text-center flat-row">
        <h3>Description</h3><br>
        <p><%= @bike.description %></p>
      </div>


    </div>
  </div>
</div>
<div class="container container-review">
  <div id="reviews">

    <% if @bike.reviews.exists? == false %>
      <h3>Be the first to leave a review for <%= @bike.brand %> <%= @bike.model %></h3>
    <% else %>
      <h3>Reviews</h3>
      <% @bike.reviews.each do |review| %>
        <%= render 'reviews/show', review: review %>
      <% end %>
    <% end %>
  </div>

  <%= render 'reviews/form', bike: @bike, review: @review %>
</div>


<%= content_for :after_js do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
      $('#sandbox-container input').datepicker({
        format: "dd/mm/yyyy",
        weekStart: 1,
        todayHighlight: true,
        startDate: new Date(),
        autoclose: true,
        calendarWeeks: true,
        datesDisabled: ['03/06/2016', '03/21/2016']
      });
    });
  <% end %>
<% end %>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

      <div class="text-center">
        <%= cl_image_tag @booking.bike.photo, height: 300, width: 200, radius: 20, crop: :fit %>
        <h2><%= @booking.bike.brand %> <%= @booking.bike.model %></h2>
        <p>Checkin: <%= @booking.checkin %></p>
        <p>Checkout: <%= @booking.checkout %></p>
      </div>

    </div>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

  <%= f.button :submit %>
<% end %>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

     <h3>New Profile</h3>
     <%= render 'form' %>
     <hr>
     <%= link_to 'Return to main page', root_path %>

   </div>
 </div>
</div>

app/views/profiles/show.html.erb
<div class="container container-profile">
  <div class="row">
    <div class="col-sm-6">

      <div class="text-center">
        <%= cl_image_tag @profile.photo, width: 300, radius: 20, crop: :fit, class: "img-responsive" %>
      </div>

    </div>
    <div class="col-sm-6">

      <div class="row row-space-4">
        <div class="text-center">
          <h2><strong><%= @profile.name %></strong></h2>
          <p><%= @profile.address %></p>
          <p><%= @profile.phone_number %></p>
          <p><%= @profile.user.email %></p>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">

      <div class="bike-list text-center">
        <h3>Your bikes</h3>
        <% if  current_user.bikes.present? %>
        <% current_user.bikes.each do |bike| %>
        <ul>
          <li>
            <%= link_to bike_path(bike) do %>
            <%= cl_image_tag bike.photo, width: 60, height: 60, radius: "max", crop: :fill %> <%= bike.brand %> <%= bike.model %>
            <% end %>
          </li>
        </ul>
            <% end %>
        <% else %>
        <h5>You have no bikes listed !</h5>
        <%= link_to 'List a bike', new_bike_path, class: 'btn btn-primary btn' %>
        <% end %>
      </div>

    </div>
    <div class="col-sm-6">
      <div class="booking-list text-center">
      <h3>Your bookings</h3>
      <% if current_user.bookings.present? %>
        <% current_user.bookings.each do |booking| %>
        <ul>
          <li>
            <%= link_to bike_booking_path(booking.bike, booking) do %>
            <strong><%= booking.bike.brand %> <%= booking.bike.model %></strong> booked from <%= booking.checkin %> to <%= booking.checkout %>
            <% end %>
          </li>
        </ul>
        <% end %>
        <% else %>
        <h5>You have no bookings yet !</h5>
        <% end %>
      </div>
    </div>
  </div>
</div>