config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'pages#home'

  resources :bikes, only: [:index, :show, :new, :create]

  resources :bikes do
    resources :reviews, only: :create
  end

  resources :bikes do
      resources :bookings
  end

  resources :profiles do
    resources :bikes, shallow: true
  end

end

app/models/bike.rb
class Bike < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :user
  validates :model, presence: true
  validates :year, presence: true, format: {
    with: /(19|20)\d{2}/i,
    message: "should be a four-digit year"
    }
  validates :displacement, presence: true
  validates :brand, presence: true
  validates :bike_type, presence: true, inclusion: { in: %w(Moped Scooter Motorcycle), message: "%{value} is not a valid category" }
  validates :address, presence: { message: "Address must be in valid format" }
  # validates :rating, numericality: { only_integer: true,
  #   less_than_or_equal_to: 5,
  #   greater_than_or_equal_to: 0
  #   }
  # # has_one :user, through: :booking
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :bike
  belongs_to :user
  validates :checkin, presence: true
  validates :checkout, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :bike
  belongs_to :user
  validates :description, :presence => { :message => "Description is mandatory, please specify one" }, length: {minimum: 10}
  validates :rating, :presence => { :message => "Rating is mandatory, please specify one" },
  numericality: { only_integer: true,
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0
  }
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  validates :owner, inclusion: { in: [true, false] }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile, dependent: :destroy
  has_many :bikes, dependent: :destroy
  has_many :bookings
  has_many :reviews


  validates :email, presence: true, format: {
   with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
   message: "invalid email"
 }

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  after_create :send_welcome_email


   def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  # private
  def index
    @bikes = Bike.all
    # @bikes = Bike.where(address: params[:city])
    if (params[:checkin] != '' && params[:checkout] != '')
      Booking.all.each do |booking|
        if (Date.parse(params[:checkin]) >= Date.parse(booking.checkin)) && (Date.parse(params[:checkin]) <= Date.parse(booking.checkout))
          @bikes = @bikes - [Bike.find(booking.bike_id)]
        elsif  (Date.parse(params[:checkout]) >= Date.parse(booking.checkin)) && (Date.parse(params[:checkout]) <= Date.parse(booking.checkout))
          @bikes = @bikes - [Bike.find(booking.bike_id)]
        elsif Date.parse(params[:checkout]) - Date.parse(params[:checkin]) > Date.parse(booking.checkout) - Date.parse(booking.checkin)
          @bikes = @bikes - [Bike.find(booking.bike_id)]
        end
      end

    end

    @markers = Gmaps4rails.build_markers(@bikes) do |bike, marker|
      marker.lat bike.latitude
      marker.lng bike.longitude
    end
  end

  def show
    @booking = Booking.new
    @bike = Bike.find(params[:id])
    @review = Review.new
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user

    if @bike.save
      flash[:notice] = "Bike #{@bike.brand} #{@bike.model} has been created"
      redirect_to bike_path(@bike)
    else
      flash[:alert] = "Bike #{@bike.brand} #{@bike.model} has not been created"
      render :new
    end
  end

  private

  def bike_params
    params.require(:bike).permit(:description, :model, :year, :displacement, :brand, :bike_type, :address, :mileage, :rate, :photo, :photo_cache)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @bike = Bike.find(params[:bike_id])
    @review = Review.new(review_params)
    @review.bike = @bike
    @review.user = current_user
    if @review.save!
      respond_to do |format|
        format.html { redirect_to bike_path(@bike) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'bikes/show' }
        format.js
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
  def rate(note)
    return 0 if note == nil
    note
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamProject</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
</head>
<body>

    <%= render 'shared/navbar' %>

    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/footer' %>

<%= javascript_include_tag 'application'%>
<%= yield(:after_js) %>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner-home" style="background-image: url('http://wallpapercave.com/wp/mf94PuR.jpg');">

  <div class="banner-content">
    <h1 class="text-center">Two wheels, one ride</h1>

    <div class="wrapper-form">

      <form action="bikes#index" class="form-inline text-center form">
        <input id ="pac-input" type="text" class="form-control input-lg" placeholder="City"name="city" required>

        <input type="text" class="form-control input-lg datebnb" data-provide="datepicker" placeholder="Check in" name="checkin">
        <input type="text" class="form-control input-lg datebnb" data-provide="datepicker" placeholder="Check out" name="checkout">

        <select class="form-control input-lg" placeholder="Type" name="type">
          <option value="1">Type</option>
          <option value="2">Scooter</option>
          <option value="3">Motorcycle</option>
          <option value="4">Moped</option>
        </select>
        <input type="submit" class="btn btn-success btn-lg" value="Search">
      </form>
    </div>


  </div>
</div>


<h1 class="text-center">What's your type?</h1>

<div class="container container-home">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://pierreisnard.fr/wp-content/uploads/Solex-Play-5.jpg');">
        <div class="card-category">Moped</div>
        <div class="card-description">
          <h2>Simple Fun</h2>
        </div>
        <a class="card-link" href="#" ></a>
      </div>
    </div>

    <div class="col-xs-12 col-sm-4">
      <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://www.objectif-moto.com/wp-content/uploads/2015/11/yamaha-eicma-tmax-lux-max.jpg');">
        <div class="card-category">Urban</div>
        <div class="card-description">
          <h2>Clever</h2>
        </div>
        <a class="card-link" href="#" ></a>
      </div>
    </div>

    <div class="col-xs-12 col-sm-4">
      <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://o.aolcdn.com/hss/storage/adam/3dae6cd2c6dee72b5576b7521ae9f922/lead12-2014-ducati-monster-1200-s-fr.jpg');">
        <div class="card-category">Sport</div>
        <div class="card-description">
          <h2>Purist</h2>
        </div>
        <a class="card-link" href="#" ></a>
      </div>
    </div>
    <div class="col-xs-12 col-sm-8 card-margin">
      <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://www.wallpapersbyte.com/wp-content/uploads/2015/09/Piaggio-Vespa-Scooter-Road-Italy-Rome-Rear-View-Street-WallpapersByte-com-3840x2400.jpg');">
        <div class="card-category">Old School</div>
        <div class="card-description">
          <h2>Lover</h2>
        </div>
        <a class="card-link" href="#" ></a>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 card-margin">
      <div class="card-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://49.media.tumblr.com/dce37f918f38dd4576622f058e5cf77e/tumblr_nylys9BNIr1qjnl39o1_500.gif');">
        <div class="card-category">Chopper</div>
        <div class="card-description">
          <h2>Loubard</h2>
        </div>
        <a class="card-link" href="#" ></a>
      </div>
    </div>
  </div>
</div>




<div class="container container-home">
  <div class="row">

    <div class="col-xs-12 col-md-4 text-center ">
      <%= image_tag "http://cdn.quotationof.com/images/steve-mcqueen-quotes-1.jpg", class: "img-grid" %>
      <h2>Be cool</h2>
      <p>Keep it Real</p>
    </div>

    <div class="col-xs-12 col-md-4 text-center ">
      <%= image_tag "https://www.healthybodydental.com/wp-content/uploads/2015/02/Clearwater-Dentist-Patient-Forms-Icon-240x300.png", class: "img-grid" %>
      <h2>Be smart</h2>
      <p>Choose the insurance wich fit you</p>
    </div>

    <div class="col-xs-12 col-md-4 text-center ">
      <%= image_tag "logo_helmet.png", class: "img-grid" %>
      <h2>Be a Man</h2>
      <p>Wear a helmet</p>
    </div>

  </div>
</div>

<h1 class="text-center">Lifestyle</h1>

<div class="banner-lifestyle home" style="background-image: url('http://farm3.static.flickr.com/2534/4180792373_b2f7521be3_o.jpg');">

  <div class="banner-lifestyle-content">
    <h1 class="text-left">Rider</h1>
    <p>Four wheels may get you there but two will make the journey memorable</p>
  </div>
  <a class="card-link" href="#" ></a>

</div>

<%= content_for :after_js do %>

  <script type="text/javascript">
    function initializeAutocomplete(id) {
      var element = document.getElementById(id);
      if (element) {
        var autocomplete = new google.maps.places.Autocomplete(element, { types: ['geocode'] });
        google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
      }
    }

    function onPlaceChanged() {
      var place = this.getPlace();

      // console.log(place);  // Uncomment this line to view the full object returned by Google API.

      for (var i in place.address_components) {
        var component = place.address_components[i];
        for (var j in component.types) {  // Some types are ["country", "political"]
          var type_element = document.getElementById(component.types[j]);
          if (type_element) {
            type_element.value = component.long_name;
          }
        }
      }
    }

    google.maps.event.addDomListener(window, 'load', function() {
      initializeAutocomplete('pac-input');
    });

        </script>

  <%= javascript_tag do %>
    $(document).ready(function(){
      $('.datebnb').datepicker({
        format: "dd/mm/yyyy",
        weekStart: 1,
        todayHighlight: true,
        startDate: new Date(),
        autoclose: true,
        calendarWeeks: true,
        datesDisabled: ['03/06/2016', '03/21/2016']
      });
    });
  <% end %>
<% end %>



<script
src="https://maps.googleapis.com/maps/api/js?&libraries=places&key=<%= ENV['GOOGLE_API_BROWSER_KEY'] %>"
></script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <ul class="list-inline">
    <li><%= link_to "#" do %><i class="fa fa-youtube fa-lg"></i><% end %></li>
    <li><%= link_to "#" do %><i class="fa fa-instagram fa-lg"></i><% end %></li>
    <li><%= link_to "#" do %><i class="fa fa-facebook fa-lg"></i><% end %></li>
    <li><%= link_to "#" do %><i class="fa fa-twitter fa-lg"></i><% end %></li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-wagon-left">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h3 class="logo">BikeR</h3>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if  current_user.profile.present? %>
          <%= cl_image_tag current_user.profile.photo, width: 50, height: 50, crop: :fill, class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= image_tag "logo_helmet.png", class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to profile_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
            <% end %>
          </li>
          <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "List your bike"), new_bike_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <% if user_signed_in? %>

  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to profile_path(current_user) do %>
          <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
          <% end %>
        </li>
        <li>
          <%= link_to root_path do %>
          <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>

  <% end %>

</div>